server:
  port: 8766

spring:
  application:
    name: springcloud-user-reg
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/root?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka